### PR TITLE
Load fontconfig files from special "snap-override" directory

### PR DESCRIPTION
**Pull request by gunnarhj**
This is a step to achieve the goal in
https://discourse.ubuntu.com/t/36923

### CODE REVIEW

**Comment by gunnarhj** [comment]
@kenvandine wrote:
> Since this will be a config file, perhaps it would be better to put it somewhere under /etc?

Actually I had the same thought. But then I thought that since we now stop loading files from the `/etc/fonts/conf.d` directory of the system host, there is a risk that somebody decides to no longer mount it either... So I picked a directory which safely will keep being mounted by the snaps.

But sure, if you want I can change it to something else. Which directory exactly would you suggest?

**Comment by gunnarhj** [comment]
I changed it to `/etc/fonts/snap-config-hack`, after having confirmed that the FF snap sees that directory too. (Will it keep seeing it?)

**Comment by kenvandine** [comment]
> I changed it to `/etc/fonts/snap-config-hack`, after having confirmed that the FF snap sees that directory too. (Will it keep seeing it?)

Yes, it will continue to see it.  @gunnarhj one more requested change (nitpick).  Please change the directory name, perhaps /etc/fonts/snap-override ?

The snap-config-hack might be off-putting to some people.

**Comment by gunnarhj** [comment]
@kenvandine: Changed as requested. (Didn't change the branch name — hope that's ok.)

**Review by kenvandine — APPROVED** [review]
Thanks, looks good

**Pull request merged**
